Bucket url
trade-tariff/trade-tariff-platform-terraform-common pull request #1
Opened 2023-05-09 08:38 UTC by bun-camara

### Jira link

HOTT-<TODO>

### What?

I have added/removed/altered:

- [ ] Added foo in bar
- [ ] Removed baz

### Why?

I am doing this because:

-
-
-

### Have you? (optional)

- [ ] Considered downstream applications that are effected by this change
- [ ] Made the change on development and staging environments first
- [ ] Configured the applications to take advantage of your change
- [ ] Considered risks of data loss, security, etc

2023-05-10 12:54 UTC, amberstarlight commented on cloudfront-tariff-reporting.tf
> +  default_root_object = "index.html"
I don't think we need `default_root_object` here, because this bucket is just for convenient file sharing. It's [optional](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#default_root_object) in the docs, so I think we can leave it out.

2023-05-10 12:59 UTC, amberstarlight requested changes
Great work! Just a few comments for us to pick up 😄

2023-05-10 14:33 UTC, bun-camara commented on variables.tf
> +}
I initially try getting the resource from data source ref.. commit [583f1e9](https://github.com/trade-tariff/trade-tariff-platform-terraform-common/pull/1/commits/583f1e9611bcd571c36ed1dbccae48df26cd932a) but it failed, i now think it may be due to not having the provider as you measure AWS Web ACL is in us-east-1

2023-05-11 08:24 UTC, amberstarlight commented on variables.tf
> +}
Yes, I think that should work. Data sources support the `provider` meta-argument, so I'd give that a try. 😄

2023-05-11 09:58 UTC, bun-camara commented on cloudfront-tariff-reporting.tf
> +  default_root_object = "index.html"
removed

2023-05-11 15:25 UTC, amberstarlight approved these changes
Looks great! 🥳

2023-05-11 15:34 UTC, merged